### ISSUE TITLE
Button & input not aligned (mobile)

### ISSUE THREAD

**Issue by meganyin13** [meganyin13/samwise-positivity#18]
![Image from iOS](https://user-images.githubusercontent.com/20008134/78853051-f13fff00-79eb-11ea-8780-2833245bff2f.png)

**Comment by meganyin13** [comment]
fixed in #29

**Comment by ptwu** [comment]
very cool, Megan!

**Comment by meganyin13** [comment]
@ptwu smh approve that PR so we can _finally_ release to prod
